name: ⚙️ Bug Report 🪛
description: Report a bug 🪲
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for making this bug report.

        ⚠️ Mind your title. ⚠️

        - "chart stuck in deploying state" - Is not the title/description of your actual bug.
        - "chartname not working" - Is not the title/description of your actual bug.
        - Don't refer version in title.
        - Always prefix an issue with `[chart-name]`

        ---

  - type: input
    id: chart-name
    attributes:
      label: chart Name
      description: |
        The name of the chart having the issue.
    validations:
      required: true
  - type: dropdown
    id: os-version
    attributes:
      label: Operating System
      description: |
        The type and version of the operating system you are currently running.
        For TrueNAS SCALE FOUND IN: System Settings > General > OS Version
      multiple: false
      options:
        - "TrueNAS SCALE 22.12.4.2 or prior"
        - "TrueNAS SCALE 23.10.0"
        - "TrueNAS SCALE 23.10.1"
        - "TrueNAS SCALE 23.10.2"
        - "TrueNAS SCALE 24.04.0"
        - "Talos-OS 1.5"
        - "Talos-OS 1.6"
    validations:
      required: true
  - type: dropdown
    id: deployment-method
    attributes:
      label: Deployment Method
      description: |
        Please select how your deployed the Chart in question
      multiple: false
      options:
        - "TrueNAS SCALE charts"
        - "FluxCD"
        - "Kubecharts"
        - "Rancher"
        - "ArgoCD"
    validations:
      required: true
  - type: input
    id: chart-version
    attributes:
      label: Chart Version
      description: |
        The version of the chart having the issue and versions of any charts being used in conjunction.
        For SCALE, FOUND IN: charts > Installed Applications
    validations:
      required: true
  - type: textarea
    id: chart-events
    attributes:
      label: Kubernetes Events
      description: |
        Debug information from the chart(s) specifically
        For SCALE, FOUND IN: charts > Installed Applications > (Click on the chart name) > Click the caret next to chartlication events and include a screenshot here.
      render: Shell
    validations:
      required: true
  - type: textarea
    id: chart-logs
    attributes:
      label: chartlication Logs
      description: |
        Log output from the containers involved in the chart
        For SCALE, FOUND IN: charts > Installed Applications > (Click the 3 dots on the top right of the chart box) > Logs
        Open the logs for each pod used for the chart and copy/paste here.

        Note: It can take a moment for the logs to show on the logs screen.
      render: Shell
    validations:
      required: true
  - type: textarea
    id: chart-config
    attributes:
      label: Chart Configuration
      description: |
        The configuration settings for the chart.
        For Helm: your custom values.yaml file

        For SCALE:
        If possible use the edit features in your screenshot tool to highlight the portions you changed intentionally.
        FOUND IN: charts > Installed Applications > (Click the 3 dots on the top right of the chart box) > Edit
        (Make sure to include what you have changed AND what you didn't change)
    validations:
      required: true
  - type: textarea
    id: bug-report
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: To Reproduce
      description: |
        Make sure that if you follow these steps again yourself the bug hchartens again. If it doesn't it's Probably a configuration error and should be handled with a support ticket on the discord.
        Steps to reproduce the behavior:
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error.
    validations:
      required: true
  - type: textarea
    id: exp-behaviour
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to hcharten.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If chartlicable, add screenshots to help explain your problem.
    validations:
      required: true
  - type: textarea
    id: add-contaxt
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: I've read and agree with the following
      options:
        - label: I've checked all open and closed issues and my issue is not there.
          required: true
        - label: I've prefixed my issue title with `[Chart-Name]`
          required: true
